version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.0"
    shell: /bin/bash --login -eo pipefail

    steps:
      - checkout
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      - run: sudo gem install bundler
      - run: bundle install
      - run:
          name: Build and run tests
          command: bundle exec fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            LC_ALL: en_US.UTF-8
            LANG: en_US.UTF-8

      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test

